docs: add docker-compose for development env
halo-sigs/halo-plugin-template pull request #4
Opened 2022-09-14 10:56 UTC by wan92hen

2022-09-14 13:49 UTC, wan92hen commented
```release-note
docs: add docker-compose for development env
```

/cc @halo-sigs/halo

2022-09-14 13:58 UTC, ruibaby requested changes

2022-09-14 13:58 UTC, ruibaby commented on compose/README.md
> +- docker
```suggestion
- Docker
```

2022-09-14 13:58 UTC, ruibaby commented on compose/README.md
> +- docker-compose
```suggestion
- Docker Compose
```

2022-09-14 14:00 UTC, ruibaby commented
似乎也可以提供一个 VS Code 的 Dev Container 配置，但不知道目前 VS Code 的 Java 支持程度如何。

参考：https://code.visualstudio.com/docs/remote/containers

示例：https://github.com/requarks/wiki/tree/main/.devcontainer

2022-09-14 15:15 UTC, ruibaby reviewed
/lgtm

2022-09-14 15:48 UTC, guqing reviewed
/lgtm

2022-09-15 00:45 UTC, JohnNiang commented
/approve

2022-09-15 03:36 UTC, ruibaby commented
现在这个仓库还没有 [OWNERS](https://github.com/halo-dev/halo/blob/master/OWNERS)，我先手动合并。

<!--merge by ruibaby-bot-->

2022-09-15 03:36 UTC, merged